grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    restart: always
influxdb:
    image: tutum/influxdb
    ports:
    - "8083:8083"
    - "8086:8086"
    expose:
    - "3000"
    - "8000"
    environment:
        PRE_CREATE_DB : 'cpu01;db1;'
    restart: always
telegraf:
    image: bbailey/telegraf
    ports:
    - "5000:5000"
    volumes:
    - ./config:/config
    restart: always
